### ISSUE TITLE
Python 3.7.2 source code install failed

### ISSUE THREAD

**Issue by gaxuhongyu** [MiCHiLU/python-functools32#11]
ENV:
Python 3.7.2 (default, Feb 12 2019, 08:15:36) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin

`
⇒  python setup.py install

This backport is for Python 2.7 only.
`

**Comment by jabdoa2** [comment]
Just use functools instead of functools32. The latter is a backport of the former.
