### ISSUE TITLE
Faces installation issue with functools32 on python version 3.8.3. Is there any solution to this ?

### ISSUE THREAD

**Issue by dk-github-acc** [MiCHiLU/python-functools32#12]
I tried to install functools32 for python version 3.8.3 on Ubuntu 20.04.1 with pip and faced the following issue.
I searched for a solution to this issue but it seems that for functools32, python version 3.2.3 has to be used. 
Is there any solution so that functools32 can be used with python 3.8.3 ?

ERROR: Command errored out with exit status 1:
     command: ../miniconda3/envs/proj/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-yzamr6zl/functools32/setup.py'"'"'; __file__='"'"'/tmp/pip-install-yzamr6zl/functools32/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-8s2o_2fo
         cwd: /tmp/pip-install-yzamr6zl/functools32/
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by jabdoa2** [comment]
Just use functools instead of functools32. The latter is a backport of the former.

**Comment by dk-github-acc** [comment]
So, after commenting the line in the code: 
`from functools32 import lru_cache `
I tried this and this is working. Did you mean this?  Thanks.

The code snippet below is from code in repository [deep-parking](https://github.com/fabiocarrara/deep-parking.git)  by Fabio Carrara

![Changes done in code](https://github.com/dk-github-acc/use-images/blob/main/functools32.png)
![functools32](https://user-images.githubusercontent.com/53915310/105637840-8c2f9a00-5e95-11eb-8caa-93caa87bbb99.png)
